// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*! 
 * @file hallo.h
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifndef _hallo_H_
#define _hallo_H_

// TODO Poner en el contexto.

#include <stdint.h>
#include <array>
#include <string>
#include <vector>

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif
#else
#define eProsima_user_DllExport
#endif

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(hallo_SOURCE)
#define hallo_DllAPI __declspec( dllexport )
#else
#define hallo_DllAPI __declspec( dllimport )
#endif // hallo_SOURCE
#else
#define hallo_DllAPI
#endif
#else
#define hallo_DllAPI
#endif // _WIN32

namespace eprosima
{
    namespace fastcdr
    {
        class Cdr;
    }
}

namespace airvision
{
    namespace contracts
    {
        /*!
         * @brief This class represents the structure point_cloud_response defined by the user in the IDL file.
         * @ingroup HALLO
         */
        class point_cloud_response
        {
        public:

            /*!
             * @brief Default constructor.
             */
            eProsima_user_DllExport point_cloud_response();
            
            /*!
             * @brief Default destructor.
             */
            eProsima_user_DllExport ~point_cloud_response();
            
            /*!
             * @brief Copy constructor.
             * @param x Reference to the object airvision::contracts::point_cloud_response that will be copied.
             */
            eProsima_user_DllExport point_cloud_response(const point_cloud_response &x);
            
            /*!
             * @brief Move constructor.
             * @param x Reference to the object airvision::contracts::point_cloud_response that will be copied.
             */
            eProsima_user_DllExport point_cloud_response(point_cloud_response &&x);
            
            /*!
             * @brief Copy assignment.
             * @param x Reference to the object airvision::contracts::point_cloud_response that will be copied.
             */
            eProsima_user_DllExport point_cloud_response& operator=(const point_cloud_response &x);
            
            /*!
             * @brief Move assignment.
             * @param x Reference to the object airvision::contracts::point_cloud_response that will be copied.
             */
            eProsima_user_DllExport point_cloud_response& operator=(point_cloud_response &&x);
            
            /*!
             * @brief This function sets a value in member index
             * @param _index New value for member index
             */
            inline eProsima_user_DllExport void index(uint32_t _index)
            {
                m_index = _index;
            }

            /*!
             * @brief This function returns the value of member index
             * @return Value of member index
             */
            inline eProsima_user_DllExport uint32_t index() const
            {
                return m_index;
            }

            /*!
             * @brief This function returns a reference to member index
             * @return Reference to member index
             */
            inline eProsima_user_DllExport uint32_t& index()
            {
                return m_index;
            }
            /*!
             * @brief This function copies the value in member data
             * @param _data New value to be copied in member data
             */
            inline eProsima_user_DllExport void data(const std::vector<char> &_data)
            {
                m_data = _data;
            }

            /*!
             * @brief This function moves the value in member data
             * @param _data New value to be moved in member data
             */
            inline eProsima_user_DllExport void data(std::vector<char> &&_data)
            {
                m_data = std::move(_data);
            }

            /*!
             * @brief This function returns a constant reference to member data
             * @return Constant reference to member data
             */
            inline eProsima_user_DllExport const std::vector<char>& data() const
            {
                return m_data;
            }

            /*!
             * @brief This function returns a reference to member data
             * @return Reference to member data
             */
            inline eProsima_user_DllExport std::vector<char>& data()
            {
                return m_data;
            }
            /*!
             * @brief This function copies the value in member filename
             * @param _filename New value to be copied in member filename
             */
            inline eProsima_user_DllExport void filename(const std::string &_filename)
            {
                m_filename = _filename;
            }

            /*!
             * @brief This function moves the value in member filename
             * @param _filename New value to be moved in member filename
             */
            inline eProsima_user_DllExport void filename(std::string &&_filename)
            {
                m_filename = std::move(_filename);
            }

            /*!
             * @brief This function returns a constant reference to member filename
             * @return Constant reference to member filename
             */
            inline eProsima_user_DllExport const std::string& filename() const
            {
                return m_filename;
            }

            /*!
             * @brief This function returns a reference to member filename
             * @return Reference to member filename
             */
            inline eProsima_user_DllExport std::string& filename()
            {
                return m_filename;
            }
            
            /*!
             * @brief This function returns the maximum serialized size of an object
             * depending on the buffer alignment.
             * @param current_alignment Buffer alignment.
             * @return Maximum serialized size.
             */
            eProsima_user_DllExport static size_t getMaxCdrSerializedSize(size_t current_alignment = 0);

            /*!
             * @brief This function returns the serialized size of a data depending on the buffer alignment.
             * @param data Data which is calculated its serialized size.
             * @param current_alignment Buffer alignment.
             * @return Serialized size.
             */
            eProsima_user_DllExport static size_t getCdrSerializedSize(const airvision::contracts::point_cloud_response& data, size_t current_alignment = 0);


            /*!
             * @brief This function serializes an object using CDR serialization.
             * @param cdr CDR serialization object.
             */
            eProsima_user_DllExport void serialize(eprosima::fastcdr::Cdr &cdr) const;

            /*!
             * @brief This function deserializes an object using CDR serialization.
             * @param cdr CDR serialization object.
             */
            eProsima_user_DllExport void deserialize(eprosima::fastcdr::Cdr &cdr);



            /*!
             * @brief This function returns the maximum serialized size of the Key of an object
             * depending on the buffer alignment.
             * @param current_alignment Buffer alignment.
             * @return Maximum serialized size.
             */
            eProsima_user_DllExport static size_t getKeyMaxCdrSerializedSize(size_t current_alignment = 0);

            /*!
             * @brief This function tells you if the Key has been defined for this type
             */
            eProsima_user_DllExport static bool isKeyDefined();

            /*!
             * @brief This function serializes the key members of an object using CDR serialization.
             * @param cdr CDR serialization object.
             */
            eProsima_user_DllExport void serializeKey(eprosima::fastcdr::Cdr &cdr) const;
            
        private:
            uint32_t m_index;
            std::vector<char> m_data;
            std::string m_filename;
        };
        /*!
         * @brief This class represents the structure point_cloud_request defined by the user in the IDL file.
         * @ingroup HALLO
         */
        class point_cloud_request
        {
        public:

            /*!
             * @brief Default constructor.
             */
            eProsima_user_DllExport point_cloud_request();
            
            /*!
             * @brief Default destructor.
             */
            eProsima_user_DllExport ~point_cloud_request();
            
            /*!
             * @brief Copy constructor.
             * @param x Reference to the object airvision::contracts::point_cloud_request that will be copied.
             */
            eProsima_user_DllExport point_cloud_request(const point_cloud_request &x);
            
            /*!
             * @brief Move constructor.
             * @param x Reference to the object airvision::contracts::point_cloud_request that will be copied.
             */
            eProsima_user_DllExport point_cloud_request(point_cloud_request &&x);
            
            /*!
             * @brief Copy assignment.
             * @param x Reference to the object airvision::contracts::point_cloud_request that will be copied.
             */
            eProsima_user_DllExport point_cloud_request& operator=(const point_cloud_request &x);
            
            /*!
             * @brief Move assignment.
             * @param x Reference to the object airvision::contracts::point_cloud_request that will be copied.
             */
            eProsima_user_DllExport point_cloud_request& operator=(point_cloud_request &&x);
            
            /*!
             * @brief This function copies the value in member msg
             * @param _msg New value to be copied in member msg
             */
            inline eProsima_user_DllExport void msg(const std::string &_msg)
            {
                m_msg = _msg;
            }

            /*!
             * @brief This function moves the value in member msg
             * @param _msg New value to be moved in member msg
             */
            inline eProsima_user_DllExport void msg(std::string &&_msg)
            {
                m_msg = std::move(_msg);
            }

            /*!
             * @brief This function returns a constant reference to member msg
             * @return Constant reference to member msg
             */
            inline eProsima_user_DllExport const std::string& msg() const
            {
                return m_msg;
            }

            /*!
             * @brief This function returns a reference to member msg
             * @return Reference to member msg
             */
            inline eProsima_user_DllExport std::string& msg()
            {
                return m_msg;
            }
            /*!
             * @brief This function sets a value in member index
             * @param _index New value for member index
             */
            inline eProsima_user_DllExport void index(int32_t _index)
            {
                m_index = _index;
            }

            /*!
             * @brief This function returns the value of member index
             * @return Value of member index
             */
            inline eProsima_user_DllExport int32_t index() const
            {
                return m_index;
            }

            /*!
             * @brief This function returns a reference to member index
             * @return Reference to member index
             */
            inline eProsima_user_DllExport int32_t& index()
            {
                return m_index;
            }
            
            /*!
             * @brief This function returns the maximum serialized size of an object
             * depending on the buffer alignment.
             * @param current_alignment Buffer alignment.
             * @return Maximum serialized size.
             */
            eProsima_user_DllExport static size_t getMaxCdrSerializedSize(size_t current_alignment = 0);

            /*!
             * @brief This function returns the serialized size of a data depending on the buffer alignment.
             * @param data Data which is calculated its serialized size.
             * @param current_alignment Buffer alignment.
             * @return Serialized size.
             */
            eProsima_user_DllExport static size_t getCdrSerializedSize(const airvision::contracts::point_cloud_request& data, size_t current_alignment = 0);


            /*!
             * @brief This function serializes an object using CDR serialization.
             * @param cdr CDR serialization object.
             */
            eProsima_user_DllExport void serialize(eprosima::fastcdr::Cdr &cdr) const;

            /*!
             * @brief This function deserializes an object using CDR serialization.
             * @param cdr CDR serialization object.
             */
            eProsima_user_DllExport void deserialize(eprosima::fastcdr::Cdr &cdr);



            /*!
             * @brief This function returns the maximum serialized size of the Key of an object
             * depending on the buffer alignment.
             * @param current_alignment Buffer alignment.
             * @return Maximum serialized size.
             */
            eProsima_user_DllExport static size_t getKeyMaxCdrSerializedSize(size_t current_alignment = 0);

            /*!
             * @brief This function tells you if the Key has been defined for this type
             */
            eProsima_user_DllExport static bool isKeyDefined();

            /*!
             * @brief This function serializes the key members of an object using CDR serialization.
             * @param cdr CDR serialization object.
             */
            eProsima_user_DllExport void serializeKey(eprosima::fastcdr::Cdr &cdr) const;
            
        private:
            std::string m_msg;
            int32_t m_index;
        };
    }
}

#endif // _hallo_H_